import {PRODUCTS,TIERS,byId,cents,retailTarget,eligible,fastSeller,recommended,totalQty,value,initialState,available,setPull,setDraftQty,autoFill,pack,sendTransfer,validState} from './demo.js';
const KEY='scout-routing-demo-v1';
let state=initialState(), storageWarning=false;
try { const stored=localStorage.getItem(KEY); if(stored){const parsed=JSON.parse(stored);if(validState(parsed))state=parsed;else storageWarning=true;} } catch { storageWarning=true; }
const main=document.querySelector('#main'), dialog=document.querySelector('#dialog');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n/100);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(text,type='')=>`<span class="badge ${type}">${text}</span>`;
const iconProduct=p=>`<span class="product-mark cat-${p.category.toLowerCase()}">${p.mark}</span>`;
const productCell=p=>`<div class="product-cell">${iconProduct(p)}<div><button class="product-link" data-action="product" data-id="${p.id}">${p.name}</button><small>${p.detail}</small></div></div>`;
const fast=()=>PRODUCTS.filter(fastSeller).sort((a,b)=>b.sold-a.sold);
const allQty=PRODUCTS.reduce((s,p)=>s+p.qty,0);
const heldQty=PRODUCTS.filter(p=>!eligible(p)).reduce((s,p)=>s+p.qty,0);
const knownValue=PRODUCTS.filter(eligible).reduce((s,p)=>s+cents(p.price)*p.qty,0);
const remainingQty=()=>PRODUCTS.filter(eligible).reduce((s,p)=>s+available(state,p.id),0);
const remainingValue=()=>PRODUCTS.filter(eligible).reduce((s,p)=>s+available(state,p.id)*cents(p.price),0);
const packedQty=()=>state.pallets.reduce((s,p)=>s+totalQty(p.items),0);
const packedValue=()=>state.pallets.reduce((s,p)=>s+value(p.items),0);
const view=()=>['overview','analysis','singles','pallets','dispatch'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
const button=(label,action,extra='',cls='')=>`<button class="button ${cls}" data-action="${action}" ${extra}>${label}</button>`;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('Browser storage is unavailable. Changes last only for this session.');}}
let toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),5000);}
function header(eyebrow,title,description,actions='') {return `<div class="workspace-head"><div><div class="eyebrow">${eyebrow}</div><h2>${title}</h2><p>${description}</p></div><div class="head-actions">${actions}</div></div>`;}
function batchStrip(){return `<div class="batch-strip"><div><span class="batch-symbol">▦</span><strong>Mixed merchandise / Batch 024</strong><span class="muted">Sample completed analysis</span></div>${badge('✓ ANALYSIS COMPLETE','positive')}<button class="text-button" data-action="navigate" data-view="analysis">View results ↗</button></div>`;}
function stat(label,number,note,accent=false){return `<div class="stat"><span class="small-label">${label}</span><strong class="${accent?'lime':''}">${number}</strong><span class="stat-note">${note}</span></div>`;}
function spark(p){const points=p.trend.map((n,i)=>`${i*23},${28-(n/Math.max(...p.trend,1))*23}`).join(' ');return `<svg class="spark" viewBox="0 0 72 32" role="img" aria-label="Monthly units sold: ${p.trend.join(', ')}"><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="1.7"/><circle cx="69" cy="${28-(p.trend[3]/Math.max(...p.trend,1))*23}" r="2.4" fill="currentColor"/></svg>`;}
function overview(){
  const pull=totalQty(state.pulls), remaining=remainingQty(), packed=packedQty();
  return header('01 / ROUTING OVERVIEW','Good inventory. Better decisions.','Pull what sells. Give everything else a place.',button('↓ Export routing plan','export-all'))+
    batchStrip()+`<div class="stats panel">${stat('ANALYZED INVENTORY',allQty,'16 product lines · '+heldQty+' units on hold')}${stat('READY RETAIL VALUE',money(knownValue),'Illustrative prices · excludes holds')}${stat('RESERVED FOR SINGLES',pull,fast().length+' fast-selling SKUs identified',true)}${stat('AVAILABLE FOR PALLETS',remaining,money(remainingValue())+' in retail value')}</div>
    <div class="overview-split"><section class="panel"><div class="section-head"><div><span class="section-index">01</span><h3>Send the best sellers first.</h3></div>${badge('STORE MATCHED','positive')}</div><p class="section-sub">Ranked by 30-day unit sales at Main Street. Only exact SKU matches qualify.</p>
      <div class="table-wrap"><table class="ranking-table"><thead><tr><th>PRODUCT</th><th>30D SOLD</th><th>AVG. DAYS TO SELL</th><th>7D PULL</th></tr></thead><tbody>${fast().slice(0,5).map((p,i)=>`<tr><td><div class="ranked-product"><span class="rank">0${i+1}</span>${productCell(p)}</div></td><td><strong class="mono">${p.sold}</strong>${spark(p)}</td><td><span class="speed"><span></span>${p.days} days</span></td><td class="lime mono">${state.pulls[p.id]} <span class="muted">units</span></td></tr>`).join('')}</tbody></table></div><div class="panel-foot"><span class="muted">7-day demand minus current store stock</span><button class="text-button lime" data-action="navigate" data-view="singles">Review pull list →</button></div></section>
      <section class="panel allocation"><div class="section-head"><h3>Where it goes.</h3><span class="small-label">${allQty} UNITS</span></div><div class="allocation-number">${Math.round((allQty-heldQty)/allQty*100)}<span>%</span><small>ready to route</small></div><div class="allocation-bar" role="img" aria-label="${pull} singles, ${remaining} available for pallets, ${packed} packed, ${heldQty} held"><span class="single" style="width:${pull/allQty*100}%"></span><span class="pallet" style="width:${remaining/allQty*100}%"></span><span class="packed" style="width:${packed/allQty*100}%"></span><span class="held" style="width:${heldQty/allQty*100}%"></span></div><div class="legend"><div><span><i class="single"></i>Single-item store</span><strong>${pull}</strong></div><div><span><i class="pallet"></i>Pallet inventory</span><strong>${remaining}</strong></div>${packed?`<div><span><i class="packed"></i>Packed</span><strong>${packed}</strong></div>`:''}<div><span><i class="held"></i>Needs review</span><strong>${heldQty}</strong></div></div><div class="hold-note"><span>↳</span><p><strong>Uncertainty stays visible.</strong>Unconfirmed models, unknown prices, and condition checks stay out of both queues.</p></div><button class="text-button" data-action="review-holds">Review held items ↗</button></section></div>
    <section class="tier-section"><div class="section-head no-border"><div><span class="section-index">02</span><h3>Four price points. One value rule.</h3></div><span class="small-label">MINIMUM RETAIL = SALE × 1.30</span></div><div class="tier-grid">${TIERS.map((tier,i)=>tierCard(tier,i)).join('')}</div></section>
    <div class="bottom-note"><span class="small-label">ROUTING LOGIC</span><span><span class="lime">Exact SKU match</span> → Sales velocity → Store stock gap → Singles first → Remaining stock to pallets</span></div>`;
}
function tierCard(tier,i){const count=state.pallets.filter(p=>p.tier===tier).length;return `<button class="tier-card" data-action="choose-tier" data-tier="${tier}"><span class="tier-top"><span>PALLET / 0${i+1}</span><span>↗</span></span><strong>${money(cents(tier))}<small>sale price</small></strong><div class="tier-value"><span>Minimum retail</span><b>${money(retailTarget(tier))}</b></div><div class="tier-base"><span class="lime">+30% RETAIL VALUE</span><span>${count?count+' PACKED':'BUILD PALLET →'}</span></div></button>`;}
function searchBar(placeholder,options){return `<div class="filter-bar"><label class="search"><span>⌕</span><span class="sr-only">${placeholder}</span><input id="search" type="search" placeholder="${placeholder}" autocomplete="off"></label><label class="filter-select"><span class="sr-only">Filter items</span><select id="filter">${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><span class="small-label" id="visible-count"></span></div>`;}
function routeLabel(p){return !eligible(p)?badge('ON HOLD','warning'):state.pulls[p.id]?badge('SINGLES + PALLETS','positive'):badge('PALLET INVENTORY');}
function analysis(){return header('02 / COMPLETED ANALYSIS','Every item, accounted for.','A fictional Scout output, reconciled against a sample store catalog.',button('↓ Export analysis','export-analysis'))+`<div class="stats panel">${stat('PRODUCT LINES',PRODUCTS.length,'Illustrative batch · 024')}${stat('READY UNITS',allQty-heldQty,'Identified, priced, condition-ready')}${stat('EXACT STORE MATCHES',PRODUCTS.filter(p=>p.match==='exact').length,'Product-level SKU match, not name similarity')}${stat('ON HOLD',heldQty,'3 product lines require review')}</div>
    <div class="notice"><span>ⓘ</span><p><strong>This is what a completed analysis could produce.</strong> Product identities, counts, confidence scores, retail references, and sales are made-up demo data. No live analysis has been run.</p></div><section class="panel">${searchBar('Search product, SKU, or category…',[['all','All items'],['ready','Ready to route'],['held','Needs review'],['new','No sales history']])}<div class="table-wrap"><table><thead><tr><th>IDENTIFIED PRODUCT</th><th>QTY</th><th>RETAIL / UNIT</th><th>IDENTITY CONF.</th><th>STORE MATCH</th><th>ROUTING</th></tr></thead><tbody>${PRODUCTS.map(p=>`<tr data-search="${esc(p.name+' '+p.id+' '+p.category)}" data-filter="${!eligible(p)?'held':p.match==='new'?'new':'ready'}"><td>${productCell(p)}</td><td class="mono">${p.qty}</td><td class="mono ${p.price===null?'orange':''}">${p.price===null?'Unknown':money(cents(p.price))}</td><td><span class="confidence ${p.confidence<90?'low':''}"><i style="width:${p.confidence}%"></i></span><span class="mono">${p.confidence}%</span></td><td>${p.match==='exact'?'<span class="match-dot"></span> Exact SKU':p.match==='new'?'<span class="muted">No match</span>':'<span class="orange">Unconfirmed</span>'}</td><td>${routeLabel(p)}</td></tr>`).join('')}</tbody></table><p class="empty-filter" hidden>No products match. Try a different search or filter.</p></div><div class="panel-foot"><span>Unknown ≠ zero. Held retail references are excluded from available value.</span><span class="small-label">SAMPLE DATA</span></div></section>`;}
function singles(){const pulls=totalQty(state.pulls);return header('03 / SINGLE-ITEM PULLS','Stock the shelf. Not the backroom.','Cross-reference the batch with what actually moves at your store.',button('↓ Export pull list','export-pulls'))+`<div class="destination-strip"><div><span class="location-dot"></span><strong>Main Street store</strong><span class="muted">Sample destination</span></div><span class="small-label">30-DAY SALES WINDOW · 7-DAY REPLENISHMENT</span></div><div class="stats panel">${stat('FAST-SELLING SKUS',fast().length,'≥20 sold / 30 days · ≤7 days to sell')}${stat('STORE PULL',pulls,'Reserved; excluded from pallet inventory',true)}${stat('PULL RETAIL VALUE',money(value(state.pulls)),'Reference value, not store revenue')}${stat('TRANSFER',state.transfer?'SENT':'DRAFT',state.transfer?'Simulated transfer · TRF-001':'Review quantities before dispatch')}</div>
      <section class="panel"><div class="section-head"><h3>Recommended replenishment</h3>${badge(state.transfer?'SIMULATED TRANSFER SENT':'EDITABLE PULL LIST',state.transfer?'positive':'')}</div><p class="section-sub">Pull = ceil(30-day sales ÷ 30 × 7) − store on-hand, capped by batch quantity. Slow sellers default to zero.</p>${searchBar('Search matched store products…',[['all','All exact matches'],['fast','Fast sellers'],['slow','Slower sellers']])}<div class="table-wrap"><table class="singles-table"><thead><tr><th>PRODUCT</th><th>30D SOLD</th><th>AVG. DAYS<br>TO SELL</th><th>STORE<br>ON-HAND</th><th>BATCH<br>QTY</th><th>REC.</th><th>PULL QTY</th></tr></thead><tbody>${PRODUCTS.filter(p=>eligible(p)&&p.match==='exact').sort((a,b)=>b.sold-a.sold).map(p=>`<tr data-search="${esc(p.name+' '+p.id)}" data-filter="${fastSeller(p)?'fast':'slow'}"><td>${productCell(p)}</td><td class="mono">${p.sold}${fastSeller(p)?'<span class="tiny-tag">FAST</span>':''}</td><td class="mono ${fastSeller(p)?'lime':'muted'}">${p.days}d</td><td class="mono">${p.stock}</td><td class="mono">${p.qty}</td><td class="mono muted">${recommended(p)}</td><td><input class="qty-input" aria-label="Pull quantity for ${p.name}" data-pull="${p.id}" type="number" min="0" max="${p.qty-state.pallets.reduce((s,x)=>s+(x.items[p.id]||0),0)}" step="1" value="${state.pulls[p.id]}" ${state.transfer?'disabled':''}></td></tr>`).join('')}</tbody></table><p class="empty-filter" hidden>No matched products found.</p></div></section>
      <div class="action-bar panel"><div><strong>${pulls} units <span class="muted">→ Main Street store</span></strong><small>${state.transfer?'Locked after simulated dispatch. No external systems were contacted.':'Reservations are live in this demo. Sending locks this pull list.'}</small></div>${state.transfer?badge('✓ SENT · DEMO ONLY','positive'):button('Create store transfer →','confirm-transfer',pulls?'':'disabled','primary')}</div>`;}
function pallets(){const draft=state.draft, retail=value(draft.items), target=retailTarget(draft.tier), gap=Math.max(0,target-retail), done=retail>=target;return header('04 / PALLET BUILDER','Build the value. Then wrap it.','Only inventory left after store pulls is available here.',button('Packing & dispatch ↗','navigate','data-view="dispatch"'))+
  `<div class="builder-tiers" role="group" aria-label="Pallet sale price">${TIERS.map(t=>`<button class="builder-tier ${draft.tier===t?'selected':''}" data-action="switch-tier" data-tier="${t}" aria-pressed="${draft.tier===t}"><span>SALE PRICE</span><strong>${money(cents(t))}</strong><small>${money(retailTarget(t))} minimum retail</small></button>`).join('')}</div>
  <div class="builder-grid"><section class="panel inventory-panel"><div class="section-head"><h3>Available inventory</h3><span class="small-label">${remainingQty()} UNITS</span></div><p class="section-sub">Store reservations and packed pallets are excluded. ${heldQty} held units cannot be used.</p>${searchBar('Search available inventory…',[['all','All categories'],['Kitchen','Kitchen'],['Home','Home'],['Electronics','Electronics']])}<div class="table-wrap"><table class="builder-table"><thead><tr><th>PRODUCT</th><th>RETAIL</th><th>AVAILABLE</th><th>IN PALLET</th></tr></thead><tbody>${PRODUCTS.filter(eligible).filter(p=>available(state,p.id)>0).map(p=>`<tr data-search="${esc(p.name+' '+p.id)}" data-filter="${p.category}"><td>${productCell(p)}</td><td class="mono">${money(cents(p.price))}</td><td class="mono muted">${available(state,p.id)}</td><td><div class="stepper"><button aria-label="Remove one ${p.name}" data-action="decrement" data-id="${p.id}" ${draft.items[p.id]?'':'disabled'}>−</button><input aria-label="Pallet quantity for ${p.name}" type="number" data-draft="${p.id}" min="0" max="${available(state,p.id)}" value="${draft.items[p.id]||0}"><button aria-label="Add one ${p.name}" data-action="increment" data-id="${p.id}" ${(draft.items[p.id]||0)>=available(state,p.id)?'disabled':''}>+</button></div></td></tr>`).join('')}</tbody></table><p class="empty-filter" ${remainingQty()?'hidden':''}>No available products match this selection.</p></div></section>
    <aside class="panel composition"><div class="section-head"><span class="small-label">PALLET COMPOSITION</span>${badge('DRAFT')}</div><div class="composition-body"><div class="small-label">ACCUMULATED RETAIL</div><div class="retail-total ${done?'lime':''}">${money(retail)}</div><div class="target-caption">of ${money(target)} minimum <span>${Math.round(retail/target*100)}%</span></div><div class="target-meter"><span style="width:${Math.min(100,retail/target*100)}%"></span></div><div class="target-status ${done?'lime':'orange'}">${done?'✓ Retail target reached':money(gap)+' more retail value needed'}</div><dl class="composition-stats"><div><dt>Pallet sale price</dt><dd>${money(cents(draft.tier))}</dd></div><div><dt>Retail above sale</dt><dd>${retail?((retail/cents(draft.tier)-1)*100).toFixed(1)+'%':'—'}</dd></div><div><dt>Items in this pallet</dt><dd>${totalQty(draft.items)} units / ${Object.values(draft.items).filter(Boolean).length} SKUs</dd></div></dl>
    <div class="composition-items">${Object.entries(draft.items).filter(([,q])=>q>0).length?Object.entries(draft.items).filter(([,q])=>q>0).map(([id,q])=>`<div><span><b>${q}×</b> ${byId(id).name}</span><strong>${money(q*cents(byId(id).price))}</strong></div>`).join(''):'<div class="composition-empty"><span>＋</span>Add products from inventory,<br>or auto-fill to the retail target.</div>'}</div>
    ${button('↗ Auto-fill to target','autofill','','full')}${button('Mark packed →','confirm-pack',done?'':'disabled','primary full')}<button class="text-button clear-draft" data-action="clear-draft" ${totalQty(draft.items)?'':'disabled'}>Clear composition</button><p class="composition-note">Auto-fill replaces this draft with the closest achievable retail total at or above the target. It does not optimize pallet size or category mix.</p></div></aside></div>`;}
function itemList(items){return `<div class="manifest-list">${Object.entries(items).filter(([,q])=>q>0).map(([id,q])=>`<div><span><b>${q}×</b> ${byId(id).name}</span><span class="mono">${money(cents(byId(id).price)*q)}</span></div>`).join('')}</div>`;}
function dispatch(){return header('05 / PACKING & DISPATCH','Ready for the next stop.','A clear record of what goes to the store and what gets sold by the pallet.',button('↓ Export routing plan','export-all'))+`<div class="stats panel">${stat('STORE TRANSFERS',state.transfer?1:0,state.transfer?totalQty(state.pulls)+' units · simulated sent':'No transfer sent')}${stat('PACKED PALLETS',state.pallets.length,packedQty()+' units allocated',true)}${stat('PALLET SALE TOTAL',money(state.pallets.reduce((s,p)=>s+cents(p.tier),0)),'Asking prices · not realized revenue')}${stat('PACKED RETAIL',money(packedValue()),'Accumulated demo reference value')}</div>
    <section class="panel dispatch-section"><div class="section-head"><h3>Store transfers</h3><span class="small-label">MAIN STREET STORE</span></div>${state.transfer?`<div class="transfer-record"><div class="transfer-icon">↗</div><div><strong>TRF-001 / Single-item replenishment</strong><p>${totalQty(state.pulls)} units · ${money(value(state.pulls))} retail reference · Main Street store</p></div>${badge('SENT · SIMULATED','positive')}${button('View manifest','transfer-manifest')}</div>`:`<div class="inline-empty"><span>No store transfer yet. Your ${totalQty(state.pulls)} reserved units are waiting for review.</span>${button('Review pull list →','navigate','data-view="singles"')}</div>`}</section>
    <section class="panel dispatch-section"><div class="section-head"><h3>Packed pallets</h3><span class="small-label">${state.pallets.length} COMPLETED</span></div>${state.pallets.length?`<div class="packed-grid">${state.pallets.map(p=>`<article class="packed-card"><div class="packed-head"><span class="mono">${esc(p.id)}</span>${badge('✓ PACKED','positive')}</div><strong class="packed-price">${money(cents(p.tier))}<small>sale price</small></strong><div class="packed-detail"><span>${totalQty(p.items)} units · ${Object.keys(p.items).length} SKUs</span><b class="lime">${money(value(p.items))} retail</b></div><div class="packed-target">${((value(p.items)/cents(p.tier)-1)*100).toFixed(1)}% above sale · target ${money(retailTarget(p.tier))}</div>${button('View packing manifest ↗','pallet-manifest',`data-id="${esc(p.id)}"`,'full')}</article>`).join('')}</div>`:`<div class="empty-state"><span>▦</span><h3>Your first pallet starts here.</h3><p>Choose a price tier, reach the retail target, and mark it packed.</p>${button('Build a pallet →','navigate','data-view="pallets"','primary')}</div>`}</section><div class="notice"><span>ⓘ</span><p>Packed and sent are demo statuses only. No physical goods, inventory systems, shipping labels, or store records are changed.</p></div>`;}
function render(){
  const current=view();main.innerHTML=({overview,analysis,singles,pallets,dispatch})[current]();
  document.querySelectorAll('[data-view]').forEach(a=>{if(a.closest('nav')){a.classList.toggle('active',a.dataset.view===current);if(a.dataset.view===current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}});
  document.querySelector('#pull-count').textContent=totalQty(state.pulls);
  document.querySelector('#dispatch-count').textContent=state.pallets.length+(state.transfer?1:0);
  filterRows();
}
function filterRows(){const search=document.querySelector('#search')?.value.toLowerCase()||'', filter=document.querySelector('#filter')?.value||'all';let count=0;
  main.querySelectorAll('tr[data-search]').forEach(row=>{row.hidden=!row.dataset.search.toLowerCase().includes(search)||!(filter==='all'||row.dataset.filter===filter||(view()==='analysis'&&filter==='ready'&&row.dataset.filter==='new'));if(!row.hidden)count++;});
  const label=document.querySelector('#visible-count');if(label)label.textContent=`${count} PRODUCTS`;
  const empty=document.querySelector('.empty-filter');if(empty)empty.hidden=count>0;
}
function refreshKeepingFilters(){const search=document.querySelector('#search')?.value,filter=document.querySelector('#filter')?.value;render();if(search!==undefined)document.querySelector('#search').value=search;if(filter!==undefined)document.querySelector('#filter').value=filter;filterRows();}
function navigate(target){if(view()===target)render();else location.hash=target;}
function openDialog(title,body,actions=''){document.querySelector('#dialog-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">SCOUT / DEMO WORKSPACE</div><h2 id="dialog-title">${title}</h2></div><button class="close-button" aria-label="Close dialog" data-action="close">×</button></div>${body}<div class="dialog-actions">${button('Close','close')}${actions}</div>`;dialog.showModal();}
function productDetail(id){const p=byId(id);openDialog(p.name,`<div class="product-detail-top">${iconProduct(p)}<div><strong>${p.detail}</strong><p class="mono muted">${p.id} · ${p.category}</p></div></div><div class="detail-grid"><div><span>ANALYZED QTY</span><strong>${p.qty}</strong></div><div><span>RETAIL / UNIT</span><strong>${p.price===null?'Unknown':money(cents(p.price))}</strong></div><div><span>IDENTITY CONFIDENCE</span><strong>${p.confidence}%</strong></div><div><span>CONDITION</span><strong>${p.condition}</strong></div></div><div class="notice"><p><strong>Fictional evidence, not a verified appraisal.</strong> ${p.price===null?'Price unknown; excluded from all value totals.':'Price is a rounded demonstration reference, not a researched retailer quote.'} ${!eligible(p)?'Held for identity, price, or condition review.':'Assumed identified and condition-ready for this demo.'}</p></div><h3>Store cross-reference</h3><p class="muted">${p.match==='exact'?`Exact demo SKU match. ${p.sold} units sold in 30 days; ${p.days} average days to sell; ${p.stock} on hand.`:p.match==='new'?'No matching store SKU or sales history. No inference of fast demand; eligible for pallets only.':'The model/variant is unconfirmed. Apparent sales history is not safe to use until identity is verified.'}</p><p>${fastSeller(p)?`Recommended store pull: <strong class="lime">${recommended(p)} units</strong>, to cover seven days of demand.`:!eligible(p)?'<span class="orange">Review required before routing.</span>':'No automatic store pull recommended.'}</p>`);}
function download(filename,rows){const text=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Demo CSV exported. All values are sample data.');}
const manifestRows=(items,label)=>[['DEMO ONLY',label],['SKU','Product','Quantity','Retail per unit USD','Line retail USD'],...Object.entries(items).filter(([,q])=>q>0).map(([id,q])=>[id,byId(id).name,q,byId(id).price,byId(id).price*q]),['TOTAL','',totalQty(items),'',value(items)/100]];
function exportAll(){download('DEMO-routing-plan.csv',[['DEMO ONLY','Fictional values; no live transactions'],['SKU','Product','Batch quantity','Single store reserved','Packed quantity','Available for pallets','Held quantity','Retail per unit USD'],...PRODUCTS.map(p=>[p.id,p.name,p.qty,state.pulls[p.id]||0,state.pallets.reduce((s,x)=>s+(x.items[p.id]||0),0),eligible(p)?available(state,p.id):0,eligible(p)?0:p.qty,p.price??'UNKNOWN']),[],['PALLET','Sale price USD','Target retail USD','Actual retail USD'],...state.pallets.map(p=>[p.id,p.tier,retailTarget(p.tier)/100,value(p.items)/100])]);}
function act(action,el){
  switch(action){
    case 'navigate':navigate(el.dataset.view);break;
    case 'review-holds':navigate('analysis');setTimeout(()=>{const f=document.querySelector('#filter');if(f){f.value='held';filterRows();}},0);break;
    case 'product':productDetail(el.dataset.id);break;
    case 'choose-tier':state.draft.tier=Number(el.dataset.tier);save();navigate('pallets');break;
    case 'switch-tier':state.draft.tier=Number(el.dataset.tier);save();render();break;
    case 'increment':case 'decrement':setDraftQty(state,el.dataset.id,(state.draft.items[el.dataset.id]||0)+(action==='increment'?1:-1));save();refreshKeepingFilters();break;
    case 'autofill':autoFill(state);save();refreshKeepingFilters();toast('Draft filled to '+money(value(state.draft.items))+' in sample retail value. Review the composition before packing.');break;
    case 'clear-draft':state.draft.items={};save();refreshKeepingFilters();break;
    case 'confirm-transfer':openDialog('Create a store transfer?',`<p class="muted">Simulate sending <strong class="lime">${totalQty(state.pulls)} units</strong> to Main Street store. This locks your pull quantities and keeps those units out of pallet stock. No actual transfer is made.</p>${itemList(state.pulls)}`,button('Send demo transfer →','send-transfer','','primary'));break;
    case 'send-transfer':sendTransfer(state);save();dialog.close();render();toast('TRF-001 sent in the demo. No real store was contacted.');break;
    case 'confirm-pack':openDialog('Mark this pallet packed?',`<p class="muted">Reserve these ${totalQty(state.draft.items)} units for a <strong>${money(cents(state.draft.tier))}</strong> pallet. Sample accumulated retail: <strong class="lime">${money(value(state.draft.items))}</strong> / ${money(retailTarget(state.draft.tier))} minimum.</p>${itemList(state.draft.items)}<p class="muted">Confirm after checking the composition. This is a simulated packing record only.</p>`,button('Confirm demo packing →','pack','','primary'));break;
    case 'pack':{const p=pack(state);save();dialog.close();render();toast(p.id+' marked packed. Inventory has been updated in this demo.');break;}
    case 'transfer-manifest':openDialog('TRF-001 / Store pull',`<p class="muted">Main Street store · sent (simulated) · ${totalQty(state.pulls)} units</p>${itemList(state.pulls)}`,button('↓ Export manifest','export-pulls'));break;
    case 'pallet-manifest':{const p=state.pallets.find(p=>p.id===el.dataset.id);openDialog(esc(p.id)+' / Packing manifest',`<p class="muted">${money(cents(p.tier))} sale · ${money(value(p.items))} sample retail · ${totalQty(p.items)} units</p>${itemList(p.items)}<p class="lime">✓ Meets ${money(retailTarget(p.tier))} minimum retail target.</p>`,button('↓ Export manifest','export-pallet',`data-id="${esc(p.id)}"`));break;}
    case 'export-pallet':{const p=state.pallets.find(p=>p.id===el.dataset.id);download('DEMO-'+p.id+'.csv',manifestRows(p.items,p.id+` · sale $${p.tier} · target retail $${retailTarget(p.tier)/100}`));break;}
    case 'export-pulls':download('DEMO-store-pull.csv',manifestRows(state.pulls,'Main Street store · '+(state.transfer?'Sent (simulated)':'Reserved draft')));break;
    case 'export-analysis':download('DEMO-analysis.csv',[['DEMO ONLY','All identities, quantities, prices and sales are fictional'],['SKU','Product','Quantity','Retail unit USD','Identity confidence %','Store match','Condition'],...PRODUCTS.map(p=>[p.id,p.name,p.qty,p.price??'UNKNOWN',p.confidence,p.match,p.condition])]);break;
    case 'export-all':exportAll();break;
    case 'close':dialog.close();break;
    case 'reset':state=initialState();save();dialog.close();navigate('overview');render();toast('Demo reset. Original sample inventory restored.');break;
  }
}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;try{act(el.dataset.action,el);}catch(error){toast(error.message);}});
document.querySelector('#reset-demo').addEventListener('click',()=>openDialog('Reset this demo?',`<p class="muted">Clear this browser’s demo transfers, packed pallets, and edits. Restore the original fictional batch and recommendations. No real inventory is affected.</p>`,button('Reset demo','reset','','primary')));
main.addEventListener('input',event=>{if(event.target.id==='search')filterRows();});
main.addEventListener('change',event=>{const el=event.target;if(el.id==='filter'){filterRows();return;}if(el.dataset.pull||el.dataset.draft){try{if(el.value.trim()==='')throw new Error('Enter a whole quantity, including 0.');if(el.dataset.pull)setPull(state,el.dataset.pull,Number(el.value));else setDraftQty(state,el.dataset.draft,Number(el.value));save();refreshKeepingFilters();}catch(error){toast(error.message);refreshKeepingFilters();}}});
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});window.scrollTo(0,0);});
render();
if(storageWarning)toast('Saved demo state was unavailable or invalid. A fresh sample batch has been loaded.');
